config/routes.rb
  resources :general_announcements, only: [:index, :show] do
    get   :system,                  on: :collection
  end

  resources :announcements,         only: [:index, :show] do
  end

  resources :faq_answers,           only: [:index, :show] do
  end

  get     'class_sessions/:course_id',                      to: 'class_sessions#index',         as: 'class_sessions'
  get     'class_sessions/:course_id/show',                 to: 'class_sessions#show',          as: 'class_session'
  get     'class_sessions/:course_id/announcement',         to: 'class_sessions#announcement'
  get     'class_sessions/:course_id/faq',                  to: 'class_sessions#faq'
  get     'class_sessions/:course_id/specific_page',        to: 'class_sessions#specific_page'
  get     'class_sessions/:course_id/collect_attendance',   to: 'class_sessions#collect_attendance',   as: 'collect_attendance'
  post    'class_sessions/:course_id/start_collect_attendance',   to: 'class_sessions#start_collect_attendance'
  get     'class_sessions/:course_id/stop_collect_attendance',    to: 'class_sessions#stop_collect_attendance'
  post    'class_sessions/:course_id/start_collect_late',   to: 'class_sessions#start_collect_late'
  get     'class_sessions/:course_id/recollect_or_delete_attendance',   to: 'class_sessions#recollect_or_delete_attendance'
  get     'class_sessions/:course_id/confirm_attendance',   to: 'class_sessions#confirm_attendance'
  post    'class_sessions/:course_id/recollect_attendance', to: 'class_sessions#recollect_attendance'
  post    'class_sessions/:course_id/recollect_late',       to: 'class_sessions#recollect_late'
  post    'class_sessions/:course_id/delete_attendance',    to: 'class_sessions#delete_attendance'
  get     'class_sessions/:course_id/prepare_help',         to: 'class_sessions#prepare_help'
  get     'class_sessions/:generic_page_id/questionnaire',  to: 'class_sessions#questionnaire'
  get     'class_sessions/:generic_page_id/compond',        to: 'class_sessions#compond'
  get     'class_sessions/:generic_page_id/multiplefib',    to: 'class_sessions#multiplefib'
  get     'class_sessions/:generic_page_id/essay',          to: 'class_sessions#essay'

  get     'group_folders/:course_id',                       to: 'group_folders#index',          as: 'group_folders'
  get     'group_folders/:id/show',                         to: 'group_folders#show',           as: 'group_folder'
  get     'group_folders/:id/edit',                         to: 'group_folders#edit',           as: 'edit_group_folder'
  patch   'group_folders/:id/update',                       to: 'group_folders#update'
  post    'group_folders/:id/upload',                       to: 'group_folders#upload'
  get     'group_folders/:id/material',                     to: 'group_folders#material',       as: 'material_group_folder'
  post    'group_folders/:id/confirm',                      to: 'group_folders#confirm'

  get     'faqs',                         to: 'faqs#index',               as: 'faqs'
  get     'faqs/:course_id/show',         to: 'faqs#show',                as: 'faq'
  get     'faqs/:course_id/course',       to: 'faqs#course',              as: 'faq_course'
  get     'faqs/:course_id/new',          to: 'faqs#new'
  post    'faqs/confirm',                 to: 'faqs#confirm'
  post    'faqs/create',                  to: 'faqs#create'

  get     'compounds/clear_password',           to: 'compounds#clear_password', as: 'compound_clear_password'
  get     'compounds/:id/show',                 to: 'compounds#show',           as: 'compound'
  patch   'compounds/:id/confirm',              to: 'compounds#confirm'
  patch   'compounds/:id/save',                 to: 'compounds#save'
  get     'compounds/:id/finish',               to: 'compounds#finish'
  post    'compounds/:id/password',             to: 'compounds#password'
  get     'compounds/:id/mark_password',        to: 'compounds#mark_password'
  post    'compounds/:id/mark_password',        to: 'compounds#mark_password'
  get     'compounds/:id/mark',                 to: 'compounds#mark'
  get     'compounds/:id/self_mark',            to: 'compounds#self_mark'
  patch   'compounds/:id/update_self_score',    to: 'compounds#update_self_score'

  get     'multiplefibs/clear_password',  to: 'multiplefibs#clear_password',    as: 'multiplefib_clear_password'
  get     'multiplefibs/:id/show',        to: 'multiplefibs#show',              as: 'multiplefib'
  get     'multiplefibs/:id/quiz',        to: 'multiplefibs#quiz'
  post    'multiplefibs/:id/mark',        to: 'multiplefibs#mark'
  get     'multiplefibs/help',            to: 'multiplefibs#help'
  post    'multiplefibs/:id/password',    to: 'multiplefibs#password'

  get     'questionnaires/finish',        to: 'questionnaires#finish'
  get     'questionnaires/clear_password',to: 'questionnaires#clear_password',  as: 'questionnaire_clear_password'
  get     'questionnaires/:id',           to: 'questionnaires#show',            as: 'questionnaire'
  patch   'questionnaires/:id/confirm',   to: 'questionnaires#confirm'
  patch   'questionnaires/:id/save',      to: 'questionnaires#save'
  post    'questionnaires/:id/password',  to: 'questionnaires#password'

  get     'essays/clear_password',        to: 'essays#clear_password',    as: 'essay_clear_password'
  get     'essays/:id',                   to: 'essays#show',              as: 'essays'
  post    'essays/:id/upload',            to: 'essays#upload'
  post    'essays/:id/destroy',           to: 'essays#destroy'
  post    'essays/:id/password',          to: 'essays#password'
  get     'essays/:id/file',              to: 'essays#file'
  get     'essays/:id/return_file',       to: 'essays#return_file'

  get     'results/:course_id',           to: 'results#index',            as: 'results'
  get     'results/:id/show',             to: 'results#show',             as: 'result'

  get     'essay_results',                       to: 'essay_results#index'
  get     'essay_results/:id/result',            to: 'essay_results#result',            as: 'result_essay_result'
  get     'essay_results/:id/mark',              to: 'essay_results#mark',              as: 'mark_essay_result'
  get     'essay_results/:id/file',              to: 'essay_results#file'
  get     'essay_results/:id/file_confirm',      to: 'essay_results#file_confirm'
  patch   'essay_results/:id/save',              to: 'essay_results#save'
  patch   'essay_results/:id/update_score',      to: 'essay_results#update_score'
  post    'essay_results/:id/outputcsv_scoresheet',         to: 'essay_results#outputcsv_scoresheet'
  post    'essay_results/:id/outputcsv_assignmentessay',    to: 'essay_results#outputcsv_assignmentessay'
  get     'essay_results/:id/upload',                       to: 'essay_results#upload'
  get     'essay_results/:id/upload_confirm',               to: 'essay_results#upload_confirm'
  post    'essay_results/:id/upload_confirm',               to: 'essay_results#upload_confirm'
  get     'essay_results/:id/upload_register',              to: 'essay_results#upload_register'
  get     'essay_results/:id/import_file',                  to: 'essay_results#import_file'
  get     'essay_results/:id/upload_error',                 to: 'essay_results#upload_error'
  get     'essay_results/:id/report_upload',                to: 'essay_results#report_upload'
  get     'essay_results/:id/report_upload_confirm/:user_id',  to: 'essay_results#report_upload_confirm'
  post    'essay_results/:id/import_report/:user_id',       to: 'essay_results#import_report'
  post    'essay_results/:id/send_mail',                    to: 'essay_results#send_mail'
  post    'essay_results/:id/download_report',              to: 'essay_results#download_report'
  post    'essay_results/:id/download_package',             to: 'essay_results#download_package'
  get     'essay_results/:id/history',                      to: 'essay_results#history',            as: 'result_essay_history'
  patch   'essay_results/:id/comment/:score',               to: 'essay_results#comment',            as: 'result_essay_comment'
  post    'essay_results/:id/return_report',                to: 'essay_results#return_report'
  post    'essay_results/:id/upload_return_report',         to: 'essay_results#upload_return_report',     as: 'result_essay_upload_return_report'
  patch   'essay_results/:id/save_return_report',           to: 'essay_results#save_return_report',       as: 'result_essay_save_return_report'
  get     'essay_results/:id/return_file',                  to: 'essay_results#return_file'
  delete  'essay_results/:id/destroy_upload_file',          to: 'essay_results#destroy_upload_file'

  get     'open_courses',                 to: 'open_courses#index'
  post    'open_courses/assign',          to: 'open_courses#assign'

  get     "helps",                        to: 'helps#index',              as: 'helps'
  patch   "helps/update",                 to: 'helps#update'
  get     "helps/:id/edit",               to: 'helps#edit'
  patch   "helps/:id/upload",             to: 'helps#upload'

  get     'materials/:id/azure_video',    to: 'materials#azure_video'
  resources :materials,   only: [:show] do
    get   :material_video,              on: :member
    get   :multiplefib_question_video,  on: :member
    get   :multiplefib_video,           on: :member
    get   :explain_file,                on: :member
    get   :pdf,                         on: :member
    resources :materials,   only: [:show] do
    end
  end

  get     "supports",               to: 'supports#index'

  namespace :admin do
    resources :users do
      post    :confirm,             on: :collection
      post    :outputcsv,           on: :collection
      post    :course,              on: :collection
      post    :delete,              on: :collection
    end

    resources :courses do
      post    :confirm,             on: :collection
      get     :bulk_update_search,  on: :collection

app/controllers/admin/compounds_controller.rb
#--
# Copyright (c) 2019 Fuyuki Academy
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

class Admin::CompoundsController < Teacher::CompoundsController

end

app/controllers/teacher/access_logs_controller.rb
#--
# Copyright (c) 2019 Fuyuki Academy
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

require 'csv'

class Teacher::AccessLogsController < ApplicationController
  before_action :set_courses, only: [:index]

  def index
    redirect_to admin_access_logs_path if current_user.admin?

    flash[:notice] = nil
    raise I18n.t("access_log.ACC_ACCESSLOG_ERROR1") if params[:type].blank?
    raise I18n.t("access_log.ACC_ACCESSLOG_ERROR2") if !params[:start_date].blank? && !date_valid?(params[:start_date])
    raise I18n.t("access_log.ACC_ACCESSLOG_ERROR2") if !params[:end_date].blank? && !date_valid?(params[:end_date])

    if params[:type]
      sql_texts = []
      sql_params = {}

      course = Course.where("id = ?", params[:type]).first
      assigned = course.course_assigned_users.where(user_id: current_user.id).first
      raise Forbidden if assigned.blank?

      sql_texts.push("course_access_logs.course_id = :course_id")
      sql_params[:course_id] = params[:type]

      if !params[:start_date].blank?
        sql_texts.push("course_access_logs.created_at >= :start_date")
        sql_params[:start_date] = params[:start_date] + " 00:00:00"
      end
      if !params[:end_date].blank?
        sql_texts.push("course_access_logs.created_at <= :end_date")
        sql_params[:end_date] = params[:end_date] + " 23:59:59"
      end
      if !params[:access_ip].blank?
        sql_texts.push("course_access_logs.ip like :access_ip")
        sql_params[:access_ip] = params[:access_ip] + "%"
      end
    end

    if params[:output] == "csv"
      @logs = CourseAccessLog.joins(:user).preload(:user).where(sql_texts.join(" AND "), sql_params).order("course_access_logs.created_at DESC")

      if @logs && @logs.count > 0
        bom = %w(EF BB BF).map { |e| e.hex.chr }.join
        csv_data = CSV.generate(bom) do |csv|
          @logs.each.with_index(1) do |log, index|
            line = []
            line << index
            line << log.user.get_name_no_prefix.to_s + log.user.user_name
            line << I18n.l(log.created_at)
            line << log.ip
            csv << line
          end
        end
      end

      filename = "semlog.csv"
      send_data csv_data, filename: filename

    else
      @logs = CourseAccessLog.joins(:user).preload(:user).where(sql_texts.join(" AND "), sql_params).order("course_access_logs.created_at DESC").page(params[:page])

    end

  rescue Forbidden => e
    raise e

  rescue => e
    logger.error e.backtrace.join("\n")
    @logs = nil
    flash[:notice] = e.message

  end

  def date_valid?(date)
    is_valid = false

    unless date.blank?
      date_ary = date.split("/")
      if date_ary.count == 3
        is_valid = true if Date.valid_date?(date_ary[0].to_i, date_ary[1].to_i, date_ary[2].to_i)
      end
    end

    is_valid
  end
end

app/controllers/teacher/course_specific_pages_controller.rb
#--
# Copyright (c) 2019 Fuyuki Academy
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

class Teacher::CourseSpecificPagesController < ApplicationController
  before_action :require_assigned, only: [:show, :upload, :show_file]
  before_action :set_courses, only: [:index]
  before_action :set_course, only: [:show, :upload]
  before_action :set_specific_page, only: [:show, :upload, :show_file]

  def upload
    @specific_page.file = params[:file]
    if @specific_page.save_file
      redirect_to action: :show, course_id: @specific_page
    else
      render action: :show
    end
  end

  def show_file
    if @specific_page.get_specific_page_url
      redirect_to @specific_page.get_specific_page_url
    else
      render 'not_found'
    end
  end

  private
    def set_specific_page
      @specific_page = SpecificPage.find(params[:course_id])
    end
end

app/views/teacher/compounds/_confirm.html.erb
<%
# Copyright (c) 2019 Fuyuki Academy
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%>

<table class="table table-striped table-hover">
  <!-- タイトル -->
  <tr>
    <td class="col-xs-3">
      <%= t("common.COMMON_SUBJECT") %>
      <span class='badge badge-essencial'>
        <%= t("common.COMMON_ESSENCIAL") %>
      </span>
    </td>
    <td class="col-xs-9">
      <%= @generic_page.generic_page_title %>
    </td>
  </tr>

  <!-- 受験回数 -->
  <tr>
    <td>
      <%= t("materials_registration.COMMONMATERIALSREGISTRATION_EXAMINATIONCOUNT") %>
    </td>
    <td>
      <%= @generic_page.max_count %>
    </td>
  </tr>

  <!-- 合格ライン -->
  <tr>
    <td>
      <%= t("materials_registration.COMMONMATERIALSREGISTRATION_PASSINGMARK") %>
    </td>
    <td>
      <%= @generic_page.pass_grade %>
      <%= t("materials_registration.COMMONMATERIALSREGISTRATION_POINT") %>
      <%= t("materials_registration.COMMONMATERIALSREGISTRATION_PASSINGMARKEXPLANATION2") %>
    </td>
  </tr>

  <!-- 添付資料 -->
  <tr>
    <td>
      <%= t("materials_registration.COMMONMATERIALSREGISTRATION_ATTACHMENT") %>
    </td>
    <td>
      <% unless @generic_page.link_name.blank? %>
        <%= t('materials_registration.COMMONMATERIALSREGISTRATION_ATTACHED') %>
        <%= link_to t("common.COMMON_READ"), material_path(@generic_page.id), {target: "_blank"} %>
      <% end %>
    </td>
  </tr>

  <!-- 開始指示パスワード	 -->
  <tr>
    <td>
      <%= t("materials_registration.COMMONMATERIALSREGISTRATION_STARTPASSWORD") %>
    </td>
    <td>
      <%= @generic_page.start_pass %>
    </td>
  </tr>

  <!-- 受付開始時間 -->
  <tr>
    <td>
      <%= t("materials_registration.COMMONMATERIALSREGISTRATION_STARTTIME") %>
    </td>
    <td>
      <div class="col-xs-12">
        <div class="form-group">
          <div class='input-group date datetimepicker form-datetime'>
            <%= form.text_field :start_time, :data => {:date_format => 'YYYY/MM/DD HH:mm'}, :class => 'form-control', placeholder: 'YYYY/MM/DD hh:mm'  %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
    </td>
  </tr>

  <!-- 受付終了時間 -->
  <tr>
    <td>
      <%= t("materials_registration.COMMONMATERIALSREGISTRATION_DEADLINE") %>
    </td>
    <td>
      <div class="col-xs-12">
        <div class="form-group">
          <div class='input-group date datetimepicker form-datetime'>
            <%= form.text_field :end_time, :data => {:date_format => 'YYYY/MM/DD HH:mm'}, :class => 'form-control', placeholder: 'YYYY/MM/DD hh:mm'  %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
    </td>
  </tr>

  <!-- 学生による採点と採点方式 -->
  <tr>
    <td>
      <%= t("materials_registration.MAT_REG_COM_REGISTERCOMPOUND_GRADETYPE") %>
    </td>
    <td>
      <%= radio_button :generic_page, :self_type, "0", :checked => true, :class => "self_type", disabled: true %>
      <%= label_tag :self_type, t('materials_registration.MAT_REG_COM_REGISTERCOMPOUND_GRADETYPE1'), value: "0", class: "label_weight_normal" %>
      <br/>
      <%= radio_button :generic_page, :self_type, "1", :class => "self_type", disabled: true %>
      <%= label_tag :self_type, t('materials_registration.MAT_REG_COM_REGISTERCOMPOUND_GRADETYPE2'), value: "1", class: "label_weight_normal" %>
      <br/>
      <%= radio_button :generic_page, :self_type, "2", :class => "self_type", disabled: true %>
      <%= label_tag :self_type, t('materials_registration.MAT_REG_COM_REGISTERCOMPOUND_GRADETYPE3'), value: "2", class: "label_weight_normal" %>
      <br/>
      <%= t("materials_registration.MAT_REG_COM_REGISTERCOMPOUND_GRADETYPEEXPLANATION") %>
    </td>
  </tr>

  <!-- 正答表示 -->
  <tr>
    <td>
      <%= t("materials_registration.MAT_REG_COM_REGISTERCOMPOUND_CORRECT_ANSWER_DISPLAY") %>
    </td>
    <td>
      <%= check_box_tag "correct_answer_display_flag", @generic_page.correct_answer_display_flag, @generic_page.correct_answer_display_flag == 1 ? true : false, { disabled: true } %>
      <%= label_tag "correct_answer_display_flag", t('materials_registration.MAT_REG_COM_REGISTERCOMPOUND_CORRECT_ANSWER_DISPLAY_TEXT1'), class: "label_weight_normal" %>
      <br/>
      <%= t("materials_registration.MAT_REG_COM_REGISTERCOMPOUND_CORRECT_ANSWER_DISPLAY_TEXT2") %>
    </td>
  </tr>

  <!-- 採点開始パスワード	 -->
  <tr>
    <td>
      <%= t("materials_registration.MAT_REG_COM_REGISTERCOMPOUND_STARTGRADEPASSWORD") %>
    </td>
    <td>
      <%= @generic_page.self_pass %>
    </td>
  </tr>

  <!-- 授業メモ（公開メモ） -->
  <tr>
    <td>
      <%= t("materials_registration.COMMONMATERIALSREGISTRATION_OPENCOMMENT") %>
    </td>
    <td>
      <%= convert_string(@generic_page.material_memo) %>
    </td>
  </tr>
</table>

app/views/teacher/compounds/edit.html.erb
<%
# Copyright (c) 2019 Fuyuki Academy
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%>

<% breadcrumb :edit_compound, @generic_page %>

<%= render 'shared/error', :record => @generic_page %>

<!-- スマートフォンタイトル　-->
<%= render :partial => "shared/smartphone", :locals => { title: t("materials_registration.COMMONMATERIALSREGISTRATION_TITLEREGISTRATIONCOMPOUND") + t("materials_registration.COMMONMATERIALSREGISTRATION_TITLEREGISTRATIONANDEDIT") } %>

<!-- 科目名 -->
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <h5>
          <%= @generic_page.course.course_name %>
        </h5>
      </div>
    </div>
  </div>
</div>

<%= form_for :generic_page, :url => {:action => "update"}, :html => {:class => "form-horizontal", :method => :patch} do |form| %>
<!-- 入力フォーム -->
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= t("materials_registration.MAT_REG_COM_REGISTERCOMPOUND_NEWWINDOW") %>
        </h3>
      </div>
      <div class="panel-body">
        <% if @generic_page.answer_scores.count == 0 %>
          <%= render form %>
        <% else %>
          <%= render 'confirm', form: form %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- ボタン -->
  <div class="text-center">
    <div class="btn-group">
      <%= form.submit t("common.COMMON_REVISE"), class: "btn btn-primary ceas-button-margin-5" %>
      <%= link_to t("common.COMMON_RETURN"), {:action => :show, :course_id => @generic_page.course}, {:class => "btn btn-default ceas-button-margin-5"} %>
    </div>
  </div>
</div>
<% end %>